// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolCaptureAppClean.Models;

#nullable disable

namespace ToolCaptureAppClean.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107030723_AddCustomerToToolTest")]
    partial class AddCustomerToToolTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ToolCaptureAppClean.Models.BrandResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ae")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Ap")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Flutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Fz")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolTestId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Vc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToolTestId");

                    b.ToTable("BrandResults");
                });

            modelBuilder.Entity("ToolCaptureAppClean.Models.ToolTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coolant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToolTests");
                });

            modelBuilder.Entity("ToolCaptureAppClean.Models.BrandResult", b =>
                {
                    b.HasOne("ToolCaptureAppClean.Models.ToolTest", "ToolTest")
                        .WithMany("BrandResults")
                        .HasForeignKey("ToolTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolTest");
                });

            modelBuilder.Entity("ToolCaptureAppClean.Models.ToolTest", b =>
                {
                    b.Navigation("BrandResults");
                });
#pragma warning restore 612, 618
        }
    }
}
